from flask import Flask, request, jsonify
import re
from urllib.parse import urlparse

# Constants for depth limits
MIN_DEPTH = 1
MAX_DEPTH = 1000

# Constants for hit rate limits (hits per second)
MIN_HIT_RATE = 0.1
MAX_HIT_RATE = 1000.0
DEFAULT_HIT_RATE = 100.0

app = Flask(__name__)

def is_valid_url(url):
    """Validate if the provided string is a valid URL"""
    try:
        result = urlparse(url)
        return all([result.scheme, result.netloc])
    except Exception:
        return False

def validate_parameters(data):
    """Validate all input parameters and return error if any"""
    errors = []
    
    # Validate URL parameter
    if 'url' not in data:
        errors.append("Missing required parameter: url")
    elif not isinstance(data['url'], str) or not data['url'].strip():
        errors.append("Parameter 'url' must be a non-empty string")
    elif not is_valid_url(data['url']):
        errors.append("Parameter 'url' must be a valid URL")
    
    # Validate depth parameter
    if 'depth' not in data:
        errors.append("Missing required parameter: depth")
    elif not isinstance(data['depth'], int):
        errors.append("Parameter 'depth' must be an integer")
    elif data['depth'] < MIN_DEPTH:
        errors.append(f"Parameter 'depth' must be greater than 0 (minimum: {MIN_DEPTH})")
    elif data['depth'] > MAX_DEPTH:
        errors.append(f"Parameter 'depth' must not exceed {MAX_DEPTH}")
    
    # Validate optional hit_rate parameter
    if 'hit_rate' in data:
        hit_rate = data['hit_rate']
        if not isinstance(hit_rate, (int, float)):
            errors.append("Parameter 'hit_rate' must be a number")
        elif hit_rate < MIN_HIT_RATE:
            errors.append(f"Parameter 'hit_rate' must be at least {MIN_HIT_RATE}")
        elif hit_rate > MAX_HIT_RATE:
            errors.append(f"Parameter 'hit_rate' must not exceed {MAX_HIT_RATE}")
    
    return errors

def validate_search_parameters(data):
    """Validate search parameters and return error if any"""
    errors = []
    
    # Validate query parameter
    if 'query' not in data:
        errors.append("Missing required parameter: query")
    elif not isinstance(data['query'], str) or not data['query'].strip():
        errors.append("Parameter 'query' must be a non-empty string")
    
    return errors

@app.route('/crawler/start', methods=['POST'])
def start_crawler():
    """Start a crawler job with the provided parameters"""
    try:
        # Get JSON data from request
        if not request.is_json:
            return jsonify({
                "error": "Content-Type must be application/json"
            }), 400
        
        data = request.get_json()
        if not data:
            return jsonify({
                "error": "Request body must contain valid JSON"
            }), 400
        
        # Validate parameters
        validation_errors = validate_parameters(data)
        if validation_errors:
            return jsonify({
                "error": "Invalid parameters",
                "details": validation_errors
            }), 400
        
        # Extract validated parameters
        url = data['url'].strip()
        depth = data['depth']
        hit_rate = data.get('hit_rate', DEFAULT_HIT_RATE)  # Optional parameter with default
        
        # TODO: Implement actual crawler job logic here
        # For now, just return success response with job details
        
        response_data = {
            "message": "Crawler job started successfully",
            "job_id": "placeholder_job_id",  # This would be generated by actual crawler
            "parameters": {
                "url": url,
                "depth": depth,
                "hit_rate": hit_rate
            }
        }
        
        return jsonify(response_data), 201
        
    except Exception as e:
        return jsonify({
            "error": "Internal server error",
            "details": str(e)
        }), 500

@app.route('/search', methods=['POST'])
def search():
    """Search for URLs based on query string"""
    try:
        # Get JSON data from request
        if not request.is_json:
            return jsonify({
                "error": "Content-Type must be application/json"
            }), 400
        
        data = request.get_json()
        if not data:
            return jsonify({
                "error": "Request body must contain valid JSON"
            }), 400
        
        # Validate parameters
        validation_errors = validate_search_parameters(data)
        if validation_errors:
            return jsonify({
                "error": "Invalid parameters",
                "details": validation_errors
            }), 400
        
        # Extract validated parameters
        query = data['query'].strip()
        
        # TODO: Implement actual search logic here
        # For now, return mock search results
        mock_results = [
            {
                "relevant_url": "https://example.com/article-1",
                "origin_url": "https://example.com",
                "depth": 1
            },
            {
                "relevant_url": "https://example.com/docs/guide",
                "origin_url": "https://example.com",
                "depth": 2
            },
            {
                "relevant_url": "https://blog.example.com/post-1",
                "origin_url": "https://example.com",
                "depth": 1
            }
        ]
        
        response_data = {
            "query": query,
            "results": mock_results,
            "total_results": len(mock_results)
        }
        
        return jsonify(response_data), 200
        
    except Exception as e:
        return jsonify({
            "error": "Internal server error",
            "details": str(e)
        }), 500

@app.route('/health', methods=['GET'])
def health_check():
    """Simple health check endpoint"""
    return jsonify({
        "status": "healthy",
        "service": "crawler-api"
    }), 200

@app.errorhandler(404)
def not_found(error):
    return jsonify({
        "error": "Endpoint not found"
    }), 404

@app.errorhandler(405)
def method_not_allowed(error):
    return jsonify({
        "error": "Method not allowed"
    }), 405

if __name__ == '__main__':
    app.run(debug=True, host='0.0.0.0', port=5000)
